In [30]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import keras
from  keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from sklearn.model_selection import train_test_split

In [31]:
df = pd.read_csv("heart.csv")
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [32]:
df["target"].unique()

array([1, 0], dtype=int64)

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trestbps  303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalach   303 non-null    int64  
 8   exang     303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64  
 11  ca        303 non-null    int64  
 12  thal      303 non-null    int64  
 13  target    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [34]:
df.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [35]:
target = df["target"].values

In [36]:
target

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [37]:
target.shape

(303,)

In [38]:
from keras.utils import to_categorical

In [39]:
target = to_categorical(target)

In [40]:
target.shape

(303, 2)

In [41]:
features = df.drop("target",axis=1).values

In [42]:
features.shape

(303, 13)

In [43]:
n_cols = features.shape[1]

In [44]:
train_X,test_X,train_y,test_y = train_test_split(features, target, test_size=0.20, random_state=4)
print(train_X.shape,test_X.shape,train_y.shape,test_y.shape)

(242, 13) (61, 13) (242, 2) (61, 2)


In [49]:
train_X

array([[42.,  1.,  3., ...,  2.,  2.,  2.],
       [65.,  0.,  2., ...,  2.,  0.,  2.],
       [47.,  1.,  2., ...,  2.,  0.,  2.],
       ...,
       [67.,  1.,  0., ...,  1.,  2.,  3.],
       [60.,  1.,  0., ...,  1.,  2.,  3.],
       [41.,  0.,  2., ...,  2.,  0.,  2.]])

In [45]:
import tensorflow as tf

In [46]:
model = Sequential()
model.add(Dense(32,activation='relu',input_shape=(n_cols,)))
model.add(Dense(2,activation='softmax'))

In [53]:
model.compile(optimizer= "adam",loss = "categorical_crossentropy",metrics=["accuracy"])
model.fit(train_X,train_y,epochs=50)

Epoch 1/50
242/242 [==============================] - 0s 338us/step - loss: 0.7202 - accuracy: 0.7066
Epoch 2/50
242/242 [==============================] - 0s 45us/step - loss: 0.7520 - accuracy: 0.7149
Epoch 3/50
242/242 [==============================] - 0s 58us/step - loss: 0.4716 - accuracy: 0.8264
Epoch 4/50
242/242 [==============================] - 0s 54us/step - loss: 0.4436 - accuracy: 0.8099
Epoch 5/50
242/242 [==============================] - 0s 49us/step - loss: 0.5116 - accuracy: 0.7727
Epoch 6/50
242/242 [==============================] - 0s 45us/step - loss: 0.4608 - accuracy: 0.8182
Epoch 7/50
242/242 [==============================] - ETA: 0s - loss: 0.2029 - accuracy: 0.90 - 0s 58us/step - loss: 0.4305 - accuracy: 0.7975
Epoch 8/50
242/242 [==============================] - 0s 56us/step - loss: 0.4011 - accuracy: 0.8347
Epoch 9/50
242/242 [==============================] - 0s 49us/step - loss: 0.3887 - accuracy: 0.8306
Epoch 10/50
242/242 [===========================

In [54]:
predictions = model.predict(test_X) # prediction for test

In [59]:
for i in range(0,50):
    pr = np.argmax(predictions[i])
    print(pr)

0
0
0
1
0
0
0
1
0
0
0
1
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
1
0
0
0
0
1
0
0
1
1
0
0
0
0
0
0
0
1
0
0
0
0
1


In [60]:
mod = Sequential()
mod.add(Dense(32,activation='relu',input_shape=(n_cols,)))
mod.add(Dense(2,activation='softmax'))
mod.compile(optimizer= "adam",loss = "categorical_crossentropy",metrics=["accuracy"])

In [61]:
mod.fit(features,target,epochs=50)

Epoch 1/50
303/303 [==============================] - 0s 276us/step - loss: 2.3249 - accuracy: 0.6139
Epoch 2/50
303/303 [==============================] - 0s 39us/step - loss: 1.8755 - accuracy: 0.6337
Epoch 3/50
303/303 [==============================] - 0s 36us/step - loss: 1.6997 - accuracy: 0.6436
Epoch 4/50
303/303 [==============================] - 0s 43us/step - loss: 1.6946 - accuracy: 0.6403
Epoch 5/50
303/303 [==============================] - 0s 43us/step - loss: 1.5589 - accuracy: 0.6337
Epoch 6/50
303/303 [==============================] - 0s 39us/step - loss: 1.4956 - accuracy: 0.6832
Epoch 7/50
303/303 [==============================] - 0s 36us/step - loss: 1.4082 - accuracy: 0.6535
Epoch 8/50
303/303 [==============================] - 0s 43us/step - loss: 1.3039 - accuracy: 0.6832
Epoch 9/50
303/303 [==============================] - 0s 43us/step - loss: 1.2592 - accuracy: 0.6568
Epoch 10/50
303/303 [==============================] - 0s 43us/step - loss: 1.1462 - accur

In [62]:
pred = model.predict(features)

In [63]:
for i in range(features.shape[0]):
    pre = np.argmax(pred[i])
    print(pre)

0
0
0
0
0
0
0
0
0
1
0
1
0
0
1
1
1
0
0
0
0
1
0
0
0
0
0
0
0
0
1
0
0
0
0
0
1
0
1
0
0
0
0
0
0
0
1
0
1
0
1
0
0
1
1
0
0
0
1
0
1
0
1
0
0
1
0
1
1
1
0
0
1
0
1
0
0
0
1
0
1
0
1
0
0
1
0
0
1
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
1
0
0
0
1
0
0
1
1
0
0
1
0
0
1
0
0
0
1
1
1
1
0
1
1
0
1
1
0
1
0
1
1
0
0
0
1
0
1
0
0
0
1
1
1
1
0
0
0
0
1
0
1
1
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
